let mongoose = require('mongoose');

module.exports = mongoose.model('oldLevel',{
    name:{
        type:String
    },
    id:{
        type:String
    },
    mobile:{
        type:Number
    },
    lvl1:[],
    lvl2:[],
    lvl3:[],
    lvl4:[],
    lvl5:[],
    lvl6:[],
    lvl7:[],
    lvl8:[],
    lvl9:[],
    lvl10:[],
    lvl11:[],
    lvl12:[],
    lvl13:[],
    lvl14:[],
    lvl15:[],
    lvl16:[],
    lvl17:[],
    lvl18:[],
    lvl19:[],
    lvl20:[],
    lvl1sum:{
        type:Number,
    },
    lvl2sum:{
        type:Number,
    },
    lvl3sum:{
        type:Number,
    },
    lvl4sum:{
        type:Number,
    },
    lvl5sum:{
        type:Number,
    },
    lvl6sum:{
        type:Number,
    },
    lvl7sum:{
        type:Number,
    },
    lvl8sum:{
        type:Number,
    },
    lvl9sum:{
        type:Number,
    },
    lvl10sum:{
        type:Number,
    },
    lvl11sum:{
        type:Number,
    },
    lvl12sum:{
        type:Number,
    },
    lvl13sum:{
        type:Number,
    },
    lvl14sum:{
        type:Number,
    },
    lvl15sum:{
        type:Number,
    },
    lvl16sum:{
        type:Number,
    },
    lvl17sum:{
        type:Number,
    },
    lvl18sum:{
        type:Number,
    },
    lvl19sum:{
        type:Number,
    },
    lvl20sum:{
        type:Number,
    },
})